name: Build C# Solution

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      id: build
      env:
        DOTNET_NOLOGO: true
      with:
        dotnet-version: '7.0.x'
    - run: dotnet build
      working-directory: Source
    - name: '.NET Version'
      run: echo '${{ steps.build.outputs.dotnet-version }}'
