name: PR Checks

on:
  pull_request:
    types: [ready_for_review, synchronize]

jobs:
  build-BE:
    if: github.event.pull_request.draft == false
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      id: build-BE
      env:
        DOTNET_NOLOGO: true
      with:
        dotnet-version: '${{ env.DOTNET_VERSION }}'
    - run: dotnet build
      working-directory: Source
    - name: '.NET Version'
      run: echo '${{ steps.build-BE.outputs.dotnet-version }}'
  test-BE:
    if: github.event.pull_request.draft == false
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-dotnet@v3
      id: test-BE
      env:
        DOTNET_NOLOGO: true
      with:
        dotnet-version: '${{ env.DOTNET_VERSION }}'
    - run: dotnet build
      working-directory: Source
    - run: dotnet test
      working-directory: Source
    - name: '.NET Version'
      run: echo '${{ steps.test-BE.outputs.dotnet-version }}'
      
