name: PR Checks

on:
  pull_request:
    types: [ready_for_review, synchronize]

jobs:
  BE:
    if: github.event.pull_request.draft == false
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
    - uses: actions/checkout@v3
    - name: 'Setup .NET Core'
    - uses: actions/setup-dotnet@v3
      id: BE
      env:
        DOTNET_NOLOGO: true
      with:
        dotnet-version: '${{ vars.DOTNET_VERSION }}'
    - name: '.NET Restore'
      run: dotnet restore
      working-directory: Source
    - name: '.NET Build'
      run: dotnet build
      working-directory: Source
    - name: '.NET Test'
      run: dotnet test
      working-directory: Source
    - name: 'Version Info'
      run: echo '.NET version ${{ steps.BE.outputs.dotnet-version }}'
      
