name: Create Release

on: 
  create

jobs:
  create-release:
    if: github.event.create.ref_type == 'tag'
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Create Release'
      run: 'gh release --tag $(git describe --tags $(git rev-list --tags --max-count=1))`
