name: Create Release Tag

on:
  push:
    branches: [production, issue-17-create-releases-on-production-pushes]
  
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: 'Get Latest Tag'
      id: get-latest-tag
      run: |
        export TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        export BUMP_INDEX=$([ "${{ vars.BUMP_TYPE }}" = "major" ] && echo "1" || ([ "${{ vars.BUMP_TYPE }}" = "minor" ] && echo "2" || echo "3"))
        echo "$BUMP_INDEX"
    - if: vars.BUMP_TYPE == 'Major'
      name: 'Bump Type: Major'
      env:
        BUMP_INDEX: 1
      run: |
        echo ${{ steps.get-latest-tag.outputs.tag }} | cut -d "." -f $BUMP_INDEX
    - if: vars.BUMP_TYPE == 'Minor'
      name: 'Bump Type: Minor'
      env:
        BUMP_INDEX: 2
      run: |
        echo ${{ steps.get-latest-tag.outputs.tag }} | cut -d "." -f $BUMP_INDEX
    - if: vars.BUMP_TYPE == 'Patch'
      name: 'Bump Type: Patch'
      env:
        BUMP_INDEX: 3
      run: |
        echo ${{ steps.get-latest-tag.outputs.tag }} | cut -d "." -f $BUMP_INDEX
        
    
