name: Create Release Tag

on:
  pull_request:
  push:
    branches: [production]
  
jobs:
  Create-Tag:
    runs-on: ubuntu-latest
    steps:
    - id: Create-Tag
    - uses: actions/checkout@v3
    - name: Bump and Push Tag
      uses: laputansoft/github-tag-action@v4.6
      with:
        github_token: ${{ secrets.ACTION_TOKEN }}
        default_bump: ${{ vars.BUMP_TYPE }}
    - name: 'Tag Info'
      run: echo 'New Tag ${{ steps.create-tag.outputs.new_tag }}'
