name: Create Release Tag

on:
  push:
    branches: [production, issue-17-create-releases-on-production-pushes]
  
jobs:
  create:
    runs-on: ubuntu-latest
    permissions: 
      contents: write
    steps:
    - uses: actions/checkout@v3
      id: create
    - name: Determine Bump Type
      run: |
        export LATEST_TAG=2
        git rev-list --tags --max-count=2
    
