name: Create Release

on: 
  create

jobs:
  create-release:
    if: github.ref_type == 'tag'
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Create Release'
      run: 'gh release create --verify-tag $(git describe)'
    env:
      GH_TOKEN: ${{ github.token }}
