name: Create Release Tag

on:
  push:
    branches: [production, issue-17-create-releases-on-production-pushes]
  
jobs:
  create:
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: 'Get Latest Tag'
      id: get-latest-tag
      run: |
        export TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "tag=$TAG" >> $GITHUB_OUTPUT
        export BUMP_INDEX=$([ "${{ vars.BUMP_TYPE }}" = "major" ] && echo "1" || ([ "${{ vars.BUMP_TYPE }}" = "minor" ] && echo "2" || echo "3"))
        echo "bump-index=$BUMP_INDEX" >> $GITHUB_OUTPUT
    - name: 'Increment Version Number'
      id: increment-version-number
      run: |
        export NUMBER_TO_BUMP=$(echo "${{ steps.get-latest-tag.outputs.tag }}" | cut -d "." -f ${{ steps.get-latest-tag.outputs.bump-index }})
        export NEW_VERSION_NUMBER=$(echo $NUMBER_TO_BUMP + 1 | bc)
        echo "$NEW_VERSION_NUMBER"
        echo "new-version-number=$NEW_VERSION_NUMBER" >> $GITHUB_OUTPUT
        
    
