name: Create Release Tag

on:
  push:
    branches: [production, issue-17-create-releases-on-production-pushes]
  
jobs:
  create:
    runs-on: ubuntu-latest
    permissions: write
    steps:
    - uses: actions/checkout@v3
      id: create
    - name: Determine Bump Type
      run: |
        echo "hello"
    
