name: Create Release Tag

on:
  push:
    branches: [production, issue-17-create-releases-on-production-pushes]
  
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - if: vars.BUMP_TYPE == Major
      env:
        BUMP_INDEX: 1
    - if: vars.BUMP_TYPE == Minor
      env:
        BUMP_INDEX: 2
    - if: vars.BUMP_TYPE == Patch
      env:
        BUMP_INDEX: 3
      id: create
    - name: Determine Bump Type
      run: |
        export LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "$LATEST_TAG"
        echo '${{ env.BUMP_INDEX }}'
        
    
