name: Create Release

on: 
  create

jobs:
  create-release:
    if: github.event.create.ref_type == 'tag' || true
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: 'Create Release'
      run: |
        'echo ${{ github.event.create.ref_type }}'
        'exit 1'
        'gh release create --tag $(git describe) --verify-tag'
