name: Create Release Tag

on:
  push:
    branches: [production, issue-17-create-releases-on-production-pushes]
  
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      id: create
    - name: Bump and Push Tag
      uses: laputansoft/github-tag-action@v4.6
      with:
        github_token: ${{ secrets.ACTION_TOKEN }}
        default_bump: ${{ vars.BUMP_TYPE }}
    - name: 'Tag Info'
      run: echo 'New Tag ${{ steps.create.outputs.new_tag }}'
