name: Create Release

on: 
  push:
    tags:
    - '**'

jobs:
  create-release:
    runs-on: ${{ vars.UBUNTU_VERSION }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v3
    - uses: ncipollo/release-action@v1
