name: Create Release Tag

on:
  push:
    branches: [production, issue-17-create-releases-on-production-pushes]
  
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
      name: 'Get Latest Tag'
    - run: |
        export LATEST_TAG=$(git describe --tags $(git rev-list --tags --max-count=1))
        echo "$LATEST_TAG"
    - if: vars.BUMP_TYPE == 'Major'
      name: 'Bump Type: Major'
      env:
        BUMP_INDEX: 1
      run: |
        echo $LATEST_TAG | cut -d "." -f $BUMP_INDEX
    - if: vars.BUMP_TYPE == 'Minor'
      name: 'Bump Type: Minor'
      env:
        BUMP_INDEX: 2
      run: |
        echo $LATEST_TAG | cut -d "." -f $BUMP_INDEX
    - if: vars.BUMP_TYPE == 'Patch'
      name: 'Bump Type: Patch'
      env:
        BUMP_INDEX: 3
      run: |
        echo $LATEST_TAG | cut -d "." -f $BUMP_INDEX
        
    
