name: Branch Pipeline

on:
  pull_request:
    types: [ready_for_review, synchronize, opened, reopened]

jobs:
  Valid-Target-Branch :
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
    - if: (github.head_ref == 'production' && github.base_ref != 'test') || (github.head_ref == 'test' && github.base_ref != 'main')
      name: 'Validate PR Target'
      run: exit 1
    - if: (github.head_ref == 'production' && github.base_ref != 'test') || (github.head_ref == 'test' && github.base_ref != 'main')
      name: 'Validate PR Target'
      run: exit 0
