name: Branch Pipeline

on:
  pull_request_target:
    types: [opened, reopened, edited]
    branches: [test, production]

jobs:
  Valid-Target-Branch :
    runs-on: ${{ vars.UBUNTU_VERSION }}
    steps:
    - if: (github.head_ref == 'production' && github.base_ref != 'test') || (github.head_ref == 'test' && github.base_ref != 'main')
      name: 'Invalid PR Target'
      run: exit 1
